version: '3.8'
services:
    mysql_srv:
        image: mysql
        container_name: mysql_ctr
        stdin_open: true
        restart: always
        environment:
            MYSQL_DATABASE: db_todo
            MYSQL_ROOT_PASSWORD: root
        ports:
            - "3307:3306"
        volumes:
            - ./data:/var/lib/mysql
            - ./conf:/etc/mysql/conf.d
            - ./logs:/logs

    phpmyadmin_srv:
        depends_on:
            - mysql_srv
        image: phpmyadmin/phpmyadmin
        container_name: phpadmin_ctr
        restart: always
        environment:
            PMA_HOST: mysql_srv
        ports:
            - 8080:80

    app_srv:
        build: 
            context: .
        depends_on:
            - mysql_srv
        environment:
            MYSQL_HOST_IP: mysql_srv
            MYSQL_USER: root
            MYSQL_DATABASE: db_todo
            MYSQL_PASSWORD: 
        ports:
            - 3003:3003
volumes:
    mysql_srv:
        driver: local